services:
  - mysql
language: python
python:
  - "3.6"
env:
  global:
    - secure: "LQDypjfjcQYVN1NYPYfBz1VqMSqjNQqEqGBp+R6u/opf8bRUtYUGdK1gR356U3ApPzgLl906M3rI2ZMNqxiROdB6RDZrDEzXLhushwCfqt0C9qmZFLsj7TtGCMT8qHahU/sfYKntYxlWDgTbvFVrHhmg6brWEObPYny5FUidJc4="
    - PATH=$PATH:`pwd`/cmd_line/enum/Linux_64bit:`pwd`/cmd_line/bader/Linux_64bit:`pwd`/cmd_line/aconvasp/Linux_64bit:`pwd`/cmd_line/boltztrap/Linux_64bit
    - GULP_LIB=`pwd`/cmd_line/gulp/Libraries
    - MPLBACKEND=Agg
# command to install dependencies
sudo: false
install:
  - pip install numpy
  - travis_wait pip install -q -r requirements.txt
  - travis_wait pip install -q -r requirements-optional.txt
# This is needed, otherwise, nosetests can't find the installed pymatgen C
# extensions.
before_script:
  - python setup.py --quiet develop
# command to run tests, e.g. python setup.py test
script: travis_wait 14400 "nosetests -v pymatgen"
notifications:
  email:
    recipients:
      - shyuep@gmail.com
    on_success: change
    on_failure: always
