services:
  - mysql
language: python
python:
  - "3.6"
env:
  global:
    - secure: "LQDypjfjcQYVN1NYPYfBz1VqMSqjNQqEqGBp+R6u/opf8bRUtYUGdK1gR356U3ApPzgLl906M3rI2ZMNqxiROdB6RDZrDEzXLhushwCfqt0C9qmZFLsj7TtGCMT8qHahU/sfYKntYxlWDgTbvFVrHhmg6brWEObPYny5FUidJc4="
    - PATH=$PATH:`pwd`/cmd_line/bader/Linux_64bit:`pwd`/cmd_line/aconvasp/Linux_64bit:`pwd`/cmd_line/boltztrap/Linux_64bit
    - GULP_LIB=`pwd`/cmd_line/gulp/Libraries
    - MPLBACKEND=Agg
    - PMG_MAPI_ENDPOINT=https://zola.lbl.gov/rest/v2
    - EXCLUDE_TESTS="--ignore=pymatgen/ext/tests/test_matproj.py"
# command to install dependencies
sudo: false
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=3.7 numpy scipy matplotlib sympy cython pandas networkx pytest h5py git
  - source activate test-environment
  - conda update --quiet --yes numpy scipy matplotlib sympy cython pandas networkx pytest pip h5py
  - pip install --quiet --ignore-installed -r requirements.txt -r requirements-optional.txt
  - >-
    echo "backend: Agg" > matplotlibrc
before_script:
  - python setup.py --quiet develop
# command to run tests, e.g. python setup.py test
script:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate test-environment
  - echo "pycodestyle->mypy->pytest->pydocstyle... Note that this fails on the first command with error."
  - echo "It is highly recommended that you use the pre-commit hook provided in pymatgen (simply copy pre-commit to .git/hooks) to check before pushing your code."
  - travis_wait 28800 pycodestyle pymatgen && mypy pymatgen && pytest $EXCLUDE_TESTS pymatgen
  - flake8 --count --show-source --statistics pymatgen
  - flake8 --count --exit-zero --max-complexity=10 --statistics pymatgen
  # Docstyle checks are enforced for files that have been modified since the v2019.10.2 tagged release.
  - export MODIFIED_FILES=`git diff --diff-filter=ACMRTUXB --name-only HEAD v2019.10.2 | grep -E 'pymatgen.*\.(py)$' | sed '/test_/d' | tr '\n' ' '`
  - pydocstyle --count pymatgen/core $MODIFIED_FILES

notifications:
  email:
    recipients:
      - shyuep@gmail.com
      - mkhorton@lbl.gov
    on_success: change
    on_failure: always
