language: python
python:
  - "2.7"
git:
  depth: 1
env:
  global:
    - secure: "hXNhTinvLDlfiIWxNgnxDFtL1zOnPd1TMyUkLLjqTRBbcuVinlMLISRgYV9g\nIIvLPG5S424ybNtU1X7X9MlypDmvis3/+G8gBo2q+7IRTAKw1C2J9/6RhIaG\nnD4aV9YZKmyz8pH1DZj6AMFIqY+2+W4Wte3oyL8IqbFRMfhdmzE="
# command to install dependencies
install: "pip install -q -r requirements.txt --use-mirrors"
# This is needed, otherwise, nosetests can't find the installed pymatgen C
# extensions.
before_script:
  - wget https://wiki.fysik.dtu.dk/ase-files/python-ase-3.6.0.2515.tar.gz
  - tar -zxf python-ase-3.6.0.2515.tar.gz
  - cd python-ase-3.6.0.2515
  - python setup.py --quiet install
  - cd ..
  - rm -rf python-ase-3.6.0.2515
  - python setup.py --quiet install
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-openbabel python-scipy
  - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages/
  - mv pymatgen pmg
  - export PATH=$PATH:$HOME/builds/materialsproject/pymatgen/cmd_line/enum/Linux_32bit
# command to run tests, e.g. python setup.py test
script: nosetests
branches:
  only:
    - master
    - stable
notifications:
  email:
    recipients:
      - pymatgen-dev@mit.edu
    on_success: change
    on_failure: always
