services:
  - mysql
language: python
python:
  - "3.7"
env:
  global:
    - secure: "LQDypjfjcQYVN1NYPYfBz1VqMSqjNQqEqGBp+R6u/opf8bRUtYUGdK1gR356U3ApPzgLl906M3rI2ZMNqxiROdB6RDZrDEzXLhushwCfqt0C9qmZFLsj7TtGCMT8qHahU/sfYKntYxlWDgTbvFVrHhmg6brWEObPYny5FUidJc4="
    - PATH=$PATH:`pwd`/cmd_line/bader/Linux_64bit:`pwd`/cmd_line/aconvasp/Linux_64bit:`pwd`/cmd_line/boltztrap/Linux_64bit
    - GULP_LIB=`pwd`/cmd_line/gulp/Libraries
    - MPLBACKEND=Agg
    - EXCLUDE_TESTS="--ignore=pymatgen/ext/tests/test_matproj.py"
# command to install dependencies
sudo: false
install:
  - pip install --quiet -r requirements.txt -r requirements-optional.txt
  - >-
    echo "backend: Agg" > matplotlibrc
before_script:
  - python setup.py --quiet develop
# command to run tests, e.g. python setup.py test
script:
  #- echo "pycodestyle->mypy->pytest->pydocstyle... Note that this fails on the first command with error."
  #- echo "It is highly recommended that you use the pre-commit hook provided in pymatgen (simply copy pre-commit to .git/hooks) to check before pushing your code."
  - travis_wait 28800 pytest $EXCLUDE_TESTS pymatgen
  #- flake8 --count --show-source --statistics pymatgen
  #- flake8 --count --exit-zero --max-complexity=10 --statistics pymatgen
  # Docstyle checks are enforced for files that have been modified since the v2020.1.28 tagged release.
  #- pydocstyle --count pymatgen

notifications:
  email:
    recipients:
      - shyuep@gmail.com
      - mkhorton@lbl.gov
    on_success: change
    on_failure: always
