language: python
python:
  - "2.7"
git:
  depth: 1
env:
  global:
    - secure: "hXNhTinvLDlfiIWxNgnxDFtL1zOnPd1TMyUkLLjqTRBbcuVinlMLISRgYV9g\nIIvLPG5S424ybNtU1X7X9MlypDmvis3/+G8gBo2q+7IRTAKw1C2J9/6RhIaG\nnD4aV9YZKmyz8pH1DZj6AMFIqY+2+W4Wte3oyL8IqbFRMfhdmzE="
before_install:
  - pip install -Iv https://bitbucket.org/jamesrhester/pycifrw/downloads/PyCifRW-3.6.1.tar.gz
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# This is needed, otherwise, nosetests can't find the installed pymatgen C
# extensions.
before_script:
  - python setup.py develop
# command to run tests, e.g. python setup.py test
script: nosetests
branches:
  only:
    - master
    - stable
    - py3k
notifications:
  email:
    recipients:
      - shyuep@gmail.com
    on_success: change
    on_failure: always
