title: MatGL
email: ongsp@ucsd.edu
description: >- # this means to ignore newlines until "baseurl:"
  A graph deep learning library for materials science.
baseurl: ""
url: "https://matgl.ai"
# twitter_username: jekyllrb
github_username:  materialsvirtuallab

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

favicon_ico: "/assets/favicon.ico"

nav_external_links:
  - title: "MatGL on GitHub"
    url: "https://github.com/materialsvirtuallab/matgl"

aux_links:
  "Materials Virtual Lab":
    - "https://materialsvirtuallab.org"