name: Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with pycodestyle
      run: |
        pip install pycodestyle --upgrade --quiet
        pycodestyle pymatgen
    - name: Lint with mypy
      run: |
        pip install mypy --upgrade --quiet
        mypy pymatgen
    - name: Lint with flake8
      run: |
        pip install flake8 --upgrade --quiet
        flake8 --count --show-source --statistics pymatgen
        # exit-zero treats all errors as warnings.
        flake8 --count --exit-zero --max-complexity=20 --statistics pymatgen
    - name: Lint with pydocstyle
      run: |
        pip install pydocstyle --upgrade --quiet
        pydocstyle --count pymatgen
    - name: Lint with pylint
      run: |
        pip install pylint --upgrade --quiet
        # stop the build if there are Python syntax errors or undefined names
        source pylint_mod.sh