name: Testing - main - Linux

on: [push, pull_request]

jobs:

  build:
    strategy:
      max-parallel: 20
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install OpenBabel and Libs
      shell: bash -l {0}
      run: |
        # Required for gulp.
        sudo apt-get install csh gfortran libgfortran3
        conda install -c conda-forge openbabel

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        # Note that this is the way to update env variables in a way that persist for the entire job.
        for pkg in `ls cmd_line`; do echo "`pwd`/cmd_line/$pkg/Linux_64bit" >> $GITHUB_PATH; done
        echo "GULP_LIB=`pwd`/cmd_line/gulp/Libraries" >> $GITHUB_ENV
        echo "PMG_TEST_FILES_DIR=`pwd`/test_files" >> $GITHUB_ENV
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-optional.txt
        pip install -r requirements-dev.txt
        pip install -e .
    - name: pytest
      shell: bash -l {0}
      env:
        PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}
        MPLBACKEND: "Agg"
        github-token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "PATH=$PATH"
        rm -rf .pytest_cache
        pytest pymatgen -rxXs --color=yes --cov=pymatgen
        coveralls